version: '3.8'

services:
  auth-backend:
    build: ./src/auth_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    networks:
      - gibsey-network

networks:
  gibsey-network:
    driver: bridge