version: '3.8'

services:
  cassandra:
    image: cassandra:5.0
    container_name: gibsey_cassandra
    ports:
      - "9042:9042"
      - "7199:7199"  # JMX port for monitoring
    environment:
      - CASSANDRA_CLUSTER_NAME=gibsey_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=16
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./scripts/cassandra_init.cql:/docker-entrypoint-initdb.d/init.cql
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - gibsey_network

volumes:
  cassandra_data:
    driver: local

networks:
  gibsey_network:
    driver: bridge